sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t kevincoakley/centos7-systemd centos/7/
    - docker build -t kevincoakley/ubuntu16.04-systemd ubuntu/16.04/
    - docker build -t kevincoakley/ubuntu18.04-systemd ubuntu/18.04/

script:
    - docker run --detach --privileged --name centos7-systemd -v /sys/fs/cgroup:/sys/fs/cgroup kevincoakley/centos7-systemd
    - bash ./tests/centos_7.sh
    - docker run --detach --privileged --name ubuntu16.04-systemd -v /sys/fs/cgroup:/sys/fs/cgroup kevincoakley/ubuntu16.04-systemd
    - bash ./tests/ubuntu_1604.sh
    - docker run --detach --privileged --name ubuntu18.04-systemd -v /sys/fs/cgroup:/sys/fs/cgroup kevincoakley/ubuntu18.04-systemd
    - bash ./tests/ubuntu_1804.sh

after_script:
    - docker ps -a
    - docker logs centos7-systemd
    - docker logs ubuntu16.04-systemd
    - docker logs ubuntu18.04-systemd
